export const BACKGROUNDS = [
  "https://images.unsplash.com/photo-1469474968028-56623f02e42e",
  "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b",
  "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05",
  "https://images.unsplash.com/photo-1441974231531-c6227db76b6e",
  "https://images.unsplash.com/photo-1472214103451-9374bd1c798e",
  "https://images.unsplash.com/photo-1682686580391-615b1f28e5ee",
  "https://images.unsplash.com/photo-1682687982501-1e58ab814714",
  "https://images.unsplash.com/photo-1682687220742-aba13b6e50ba",
];

export const FONTS = [
  { value: "font-inter", label: "Inter" },
  { value: "font-playfair", label: "Playfair Display" },
  { value: "font-montserrat", label: "Montserrat" },
  { value: "font-roboto", label: "Roboto" },
  { value: "font-lora", label: "Lora" },
  { value: "font-oswald", label: "Oswald" },
  { value: "font-raleway", label: "Raleway" },
  { value: "font-poppins", label: "Poppins" },
  { value: "font-fira-code", label: "Fira Code" },
  { value: "font-merriweather", label: "Merriweather" },
];

export const MOTIVATIONAL_QUOTES = [
  "Dream big, work hard, stay focused",
  "Your only limit is your mind",
  "Make today amazing",
  "Success is built one day at a time",
  "Push yourself, because no one else is going to do it for you",
  "The future belongs to those who believe in the beauty of their dreams",
  "Your potential is endless",
  "Great things never come from comfort zones",
  "Believe you can and you're halfway there",
  "Make it happen, shock everyone",
  "Success doesn't come to you, you go to it",
  "The harder you work, the luckier you get",
  "Your time is limited, don't waste it",
  "Dreams don't work unless you do",
  "Stay hungry, stay foolish",
  "The best way to predict the future is to create it",
  "Focus on the step in front of you, not the whole staircase",
  "You are stronger than you think",
  "Every day is a new beginning",
  "Small progress is still progress",
  "Think big, start small, act now",
  "Your attitude determines your direction",
  "Make yourself proud",
  "The only bad workout is the one that didn't happen",
  "Discipline is choosing between what you want now and what you want most",
];

export const WALLPAPER_PRESETS = [
  {
    id: "desktop-4k",
    label: "Desktop 4K",
    width: 3840,
    height: 2160,
  },
  {
    id: "desktop-2k",
    label: "Desktop 2K",
    width: 2560,
    height: 1440,
  },
  {
    id: "desktop-fhd",
    label: "Desktop Full HD",
    width: 1920,
    height: 1080,
  },
  {
    id: "iphone-14",
    label: "iPhone 14 Pro",
    width: 1179,
    height: 2556,
  },
  {
    id: "iphone-13",
    label: "iPhone 13/12",
    width: 1170,
    height: 2532,
  },
  {
    id: "ipad-pro",
    label: "iPad Pro",
    width: 2048,
    height: 2732,
  },
  {
    id: "macbook",
    label: "MacBook Pro 16\"",
    width: 3456,
    height: 2234,
  },
  {
    id: "custom",
    label: "Custom Size",
    width: 1920,
    height: 1080,
  },
];